# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=254, verbose_name='Denominazione')),
                ('indirizzo', models.CharField(max_length=254, verbose_name='Indirizzo')),
                ('cap', models.CharField(max_length=10, verbose_name='CAP')),
                ('comune', models.CharField(max_length=254, verbose_name='Comune')),
                ('provincia', models.CharField(max_length=2, verbose_name='Provincia')),
                ('nazione', models.CharField(max_length=2, verbose_name='Nazione')),
                ('regime_fiscale', models.CharField(max_length=10, verbose_name='Regime Fiscale')),
                ('partita_iva', models.CharField(max_length=20, verbose_name='Partita Iva')),
                ('indirizzo_pec', models.EmailField(blank=True, max_length=254, verbose_name='Indirizzo PEC')),
                ('codice_univoco', models.CharField(blank=True, max_length=10, verbose_name='Codice univoco')),
            ],
            options={
                'verbose_name': 'informazione cedente',
                'verbose_name_plural': 'informazione cedenti',
            },
        ),
    ]
