# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cedente', '0002_auto_20181218_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedente',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
    ]
