# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import upload_download.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fatturazione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.FileField(blank=True, upload_to='downloads/xml/', verbose_name='XML')),
                ('html', models.FileField(blank=True, upload_to='downloads/html/', verbose_name='HTML')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('lnummov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fatturazione.Fattura')),
            ],
            options={
                'verbose_name': 'Fattura da scaricare',
                'verbose_name_plural': 'Fatture da scaricare',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to=upload_download.models.UploadToPathAndRename('uploads/'), verbose_name='Nome file')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
            ],
            options={
                'verbose_name': 'file da caricare',
                'verbose_name_plural': 'files da caricare',
            },
        ),
    ]
