# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfile',
            name='lnummov',
        ),
        migrations.DeleteModel(
            name='DownloadFile',
        ),
    ]
