# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementofattura',
            name='codart',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Codice articolo'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='codmag',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Codice magazzino'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='descri',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='iva',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='lagente',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='lcprovv',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Provvigione agente 2'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='lprovv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Provvigione agente 3'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='ltprovv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Provvigione agente 1'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='nrr',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='percsc2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Percentuale sconto 2'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='percsc3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Percentuale sconto 2'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='prezzo',
            field=models.FloatField(blank=True, null=True, verbose_name='Prezzo'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='qto',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantità'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='sconto1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Percentuale sconto 1'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='tsconto',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo sconto'),
        ),
        migrations.AlterField(
            model_name='elementofattura',
            name='um',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Unità di misura'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='amezzo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Vettore'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='bappoggio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Banca d'appoggio"),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='coddes',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Codice listino'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='cprovv',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Codice provvigione'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='ddoc',
            field=models.DateField(blank=True, null=True, verbose_name='Data documento'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='gencon',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Generazione documento'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='localita',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Località'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='mopag',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Modalità pagamento'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='nrdoc',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero documento'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='pariva',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='percprovv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Percentuale provvigione'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='percsconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Percentual sconto'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='provv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Provvigione'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='rsoc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ragion sociale'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='speseboll',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Spese bollo'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='tdoc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Causale'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='tporto',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo trasporto'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='tprovv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo provvigione'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='tpsconto',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo sconto'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='vcoddes',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Codice vettore'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='vindirizzo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Indirizzo vettore'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='vlocalita',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Località vettore'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='vprovincia',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia vettore'),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='vrsoc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ragione sociale vettore'),
        ),
    ]
