# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0002_auto_20181215_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fattura',
            name='rsoc',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ragione sociale'),
        ),
    ]
