# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0004_auto_20181215_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsenzioneIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_iva', models.CharField(max_length=5, verbose_name='codice IVA')),
                ('perc_iva', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='percentuale IVA')),
                ('natura', models.CharField(max_length=5, verbose_name='natura')),
                ('riferimento_normativo', models.CharField(max_length=50, verbose_name='riferimento normativo')),
            ],
            options={
                'verbose_name_plural': 'esenzioni IVA',
                'verbose_name': 'esenzione IVA',
            },
        ),
    ]
