# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0006_auto_20200523_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esenzioneiva',
            name='riferimento_normativo',
            field=models.CharField(blank=True, max_length=50, verbose_name='riferimento normativo'),
        ),
    ]
