# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0007_auto_20200523_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esenzioneiva',
            name='codice_iva',
            field=models.CharField(max_length=5, unique=True, verbose_name='codice esenzione IVA'),
        ),
    ]
