# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0008_auto_20200523_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esenzioneiva',
            name='natura',
            field=models.CharField(choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5'), ('N6', 'N6'), ('N7', 'N7')], max_length=5, verbose_name='natura'),
        ),
    ]
