# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0013_auto_20200708_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliquotaiva',
            old_name='natura',
            new_name='natura_esenzione',
        ),
    ]
