# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0014_auto_20200708_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquotaiva',
            name='codice_iva',
            field=models.CharField(max_length=5, unique=True, verbose_name='codice IVA'),
        ),
    ]
