# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0016_auto_20200708_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquotaiva',
            name='perc_iva',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='percentuale IVA'),
        ),
    ]
