# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0019_auto_20200708_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquotaiva',
            name='riferimento_normativo_cliente',
            field=models.BooleanField(default=False, verbose_name='includere riferimento normativo cliente?'),
        ),
    ]
