# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0020_aliquotaiva_riferimento_normativo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquotaiva',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='Attiva/disattiva codice'),
        ),
    ]
