# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0021_aliquotaiva_attivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalitaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_pagamento', models.CharField(max_length=5, unique=True, verbose_name='codice IVA')),
                ('n_giorni_scadenza', models.PositiveSmallIntegerField(verbose_name='numero giorni scadenza')),
            ],
            options={
                'verbose_name': 'modalità pagamento',
                'verbose_name_plural': 'modalità pagamento',
            },
        ),
    ]
