# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0022_modalitapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalitapagamento',
            name='attivo',
            field=models.BooleanField(default=True, verbose_name='Attiva/disattiva codice'),
        ),
        migrations.AlterField(
            model_name='modalitapagamento',
            name='codice_pagamento',
            field=models.CharField(max_length=5, unique=True, verbose_name='codice pagamento'),
        ),
    ]
