# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0023_auto_20200708_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalitapagamento',
            name='codice_pagamento_fattura_elettronica',
            field=models.CharField(choices=[('MP01', 'MP01'), ('MP02', 'MP02'), ('MP03', 'MP03'), ('MP04', 'MP04'), ('MP05', 'MP05'), ('MP06', 'MP06'), ('MP07', 'MP07'), ('MP08', 'MP08'), ('MP09', 'MP09'), ('MP10', 'MP10'), ('MP11', 'MP11'), ('MP12', 'MP12'), ('MP13', 'MP13'), ('MP14', 'MP14'), ('MP15', 'MP15'), ('MP16', 'MP16'), ('MP17', 'MP17')], default='', max_length=10, verbose_name='natura esenzione'),
            preserve_default=False,
        ),
    ]
