# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0027_auto_20200708_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fattura',
            name='mopag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fatturazione.ModalitaPagamento', verbose_name='Modalità pagamento'),
        ),
    ]
