# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codana', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Codice cliente')),
                ('intest', models.CharField(blank=True, max_length=10, null=True, verbose_name='Intestazione')),
                ('rsoc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente')),
                ('codfis', models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice fiscale')),
                ('piva', models.CharField(blank=True, max_length=11, null=True, verbose_name='Partita IVA')),
                ('indir', models.CharField(blank=True, max_length=40, null=True, verbose_name='Indirizzo')),
                ('cap', models.CharField(blank=True, max_length=5, null=True, verbose_name='CAP')),
                ('local', models.CharField(blank=True, max_length=35, null=True, verbose_name='Città')),
                ('prov', models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia')),
                ('nazione', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nazione')),
                ('allegiva', models.SmallIntegerField(blank=True, null=True)),
                ('riferiment', models.CharField(blank=True, max_length=30, null=True, verbose_name='Riferimento')),
                ('telef', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono')),
                ('fax', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fax')),
                ('ressec', models.CharField(blank=True, max_length=60, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('luona', models.CharField(blank=True, max_length=35, null=True)),
                ('provna', models.CharField(blank=True, max_length=2, null=True)),
                ('indircor', models.CharField(blank=True, max_length=40, null=True)),
                ('capcor', models.CharField(blank=True, max_length=5, null=True)),
                ('localcor', models.CharField(blank=True, max_length=35, null=True)),
                ('provcor', models.CharField(blank=True, max_length=2, null=True)),
                ('nazionecor', models.CharField(blank=True, max_length=3, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clienti',
            },
        ),
    ]
