# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafe', '0003_auto_20181215_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codice_univoco',
            field=models.CharField(blank=True, max_length=10, verbose_name='Codice univoco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indirizzo_pec',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Indirizzo PEC'),
        ),
    ]
